export const ANALYTICS_POST_REQUEST = 'ANALYTICS_POST_REQUEST';
export const ANALYTICS_POST_SUCCESS = 'ANALYTICS_POST_SUCCESS';
export const ANALYTICS_POST_FAILURE = 'ANALYTICS_POST_FAILURE';
export const ANALYTICS_POST_RESET = 'ANALYTICS_POST_RESET';
