export const ANALYTICS_POST_REQUEST = 'ANALYTICS_POST_REQUEST';
export const ANALYTICS_POST_SUCCESS = 'ANALYTICS_POST_SUCCESS';
export const ANALYTICS_POST_FAILURE = 'ANALYTICS_POST_FAILURE';
export const ANALYTICS_POST_RESET = 'ANALYTICS_POST_RESET';

export const ANALYTICS_GET_DATA_REQUEST = 'ANALYTICS_GET_DATA_REQUEST';
export const ANALYTICS_GET_DATA_SUCCESS = 'ANALYTICS_GET_DATA_SUCCESS';
export const ANALYTICS_GET_DATA_FAILURE = 'ANALYTICS_GET_DATA_FAILURE';
export const ANALYTICS_GET_DATA_RESET = 'ANALYTICS_GET_DATA_RESET';
