export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET';
export const USER_LOGOUT = 'USER_LOGOUT';

export const GOOGLE_USER_LOGIN_REQUEST = 'GOOGLE_USER_LOGIN_REQUEST';
export const GOOGLE_USER_LOGIN_SUCCESS = 'GOOGLE_USER_LOGIN_SUCCESS';
export const GOOGLE_USER_LOGIN_FAILURE = 'GOOGLE_USER_LOGIN_FAILURE';
export const GOOGLE_USER_LOGOUT = 'GOOGLE_USER_LOGOUT';
